#language: python
#python:
#    - "2.7"
addons:
  apt:
    packages:
        - gfortran 
        - libblas-dev 
        - libblas3 
        - liblapack-dev 
        - liblapack3
install:
    - cp config/make.sys.gfort make.sys
    - make -j wannier post
#before_script:
#    - ...
script:
    - make tests
