language: python
python:
    - "2.7"
addons:
  apt:
    packages:
        - gfortran 
        - libblas-dev 
        - liblapack-dev 
env:
   - W90TESTSWITHINTERFACE=true
   - W90TESTSWITHINTERFACE=false
install:
# Install Wannier
    - cp config/make.inc.gfort.travisci make.inc
    - make -j default
script:
    - ./test-suite/run_tests_travis.sh
git:
  depth: 3
